### ISSUE TITLE
Coexistence with other packages

### ISSUE THREAD

**Issue by zenny** [darkstego/wakib-keys#3]
Hi,

This is a great package :+1: , yet it appears it tends to interfere with the keybindings of the other packages including evil-mode for modal editing and scimax keybindings. For example, Ctrl+s conflicts with the ivy's search mode (swiper) among others.

Why not to make in such a way (like evil-mode)  that this package searches for existing keybindings all .el and replaces them with alternate wakib-keybindings even for other pakcages, particularly scimax (which I use)?

Just my two cents. Cheers and stay safe,
/z

**Comment by darkstego** [comment]
I don't know how to make it coexist with evil-mode since both seem to try and do the same thing and that is provide keybindings for basic functions. I am not sure I quite understand how you would use those two packages together. Are you using both of them together?

As for packages, I would like to find a way to make sure they all work well with this package. I will look into how evil-mode does it. I understand searching for keybindings, but there needs to be a method to map it to something reasonable. Typically packages work when they simply remap existing functions. So when using ivy you get counsel for file-open working out of the box. Most of ivy works fine, but I am unsure how swiper is triggered. Do you explicitly setup the keybindings for it?

I need to look into scimax to see where things are going wrong. Hopefully I find a way to make it work.

**Comment by zenny** [comment]
> I don't know how to make it coexist with evil-mode since both seem to try and do the same thing and that is provide keybindings for basic functions. I am not sure I quite understand how you would use those two packages together. Are you using both of them together?

evil-mode (vim-bindings) are great for modal editing to avoid any RSI because it tries to maintain your fingers in the home row. However, if there are alternatives (yep ctrl or Escape can be mapped to capslock key), why not go for wakib because keybindings are more user-friendly than anything else.
> 
> As for packages, I would like to find a way to make sure they all work well with this package. I will look into how evil-mode does it. I understand searching for keybindings, but there needs to be a method to map it to something reasonable. Typically packages work when they simply remap existing functions. So when using ivy you get counsel for file-open working out of the box. Most of ivy works fine, but I am unsure how swiper is triggered. Do you explicitly setup the keybindings for it?

Swiper is triggered with Ctrl+s which is equivalent to `save` in wakib, fyi. Save in default emacs is `ctrl-x ctrl-s` and in evil-mode `:w` as you are aware of.
> 
> I need to look into scimax to see where things are going wrong. Hopefully I find a way to make it work.

Appreciate that. Look forward to your inputs. To be honest, Scimax is the only configuration that I found most useful for technical writing purposes (a complete functional config). There are two parts that is not there in scimax are zettlelkaten-based stuffs like org-roam, org-brain, gkroam or org-multi-wiki and some easy keybindings to teach emacs to newbies (the latter attracted to wakib after checking several keybinding pacakges like kakoune, ergoemacs xahl keys, ryo-modal, modalka, meow among others).

**Comment by darkstego** [comment]
So looking into Scimax, I think the issue is the bindings are registered explicitly rather than as a remap. To fix this you need to change the line in scimax file packages.el
`("C-s" . counsel-grep-or-swiper)`
and replace it with 
`([remap isearch-forward] . counsel-grep-or-swiper)`

Then C-f will call swiper instead of isearch.

I did make a pull request with scimax, in hopes that the change is made upstream.

What other problems are there with scimax?

**Comment by darkstego** [comment]
The pull request was accepted into scimax so now C-f uses swiper instead of isearch if you use wakib with scimax.
