### ISSUE TITLE
Symbol's value as variable is void: mouse-wheel-down-event

### ISSUE THREAD

**Issue by gety9** [darkstego/wakib-keys#4]
Emacs 27.2 (build 1, aarch64-unknown-linux-android)

When i try to enable `wakib-keys` mode on my android device (emacs installed via termux) i am getting following error:
`Symbol's value as variable is void: mouse-wheel-down-event`

Exactly same config works fine on my Windows machine.

When googling error this seems somewhat related 
https://github.com/syl20bnr/spacemacs/issues/6865, 
https://github.com/syl20bnr/spacemacs/pull/6866/commits/9e7feee03ed5fb9aae23db0524ddfe91a6684313, 
https://github.com/syl20bnr/spacemacs/issues/4591#issuecomment-223273558

p.s. i don't have mouse on this device, just want to be able to use wakib-keys

**Comment by darkstego** [comment]
So the issue is these two lines.
```
  (,(concat "<C-" (symbol-name mouse-wheel-down-event)  ">") . text-scale-increase)
  (,(concat "<C-" (symbol-name mouse-wheel-up-event)  ">") . text-scale-decrease)
```

These add the text scaling to ctrl+ mouse wheel. These have to be evaluated dynamically because which mouse button (mouse-4,mouse-5) is up actually depends on the OS. I didn't think that an OS would not have a `mouse-wheel-down-event`. I will update it to handle this case.

**Comment by darkstego** [comment]
Should be fixed in the latest commit. Although I have no way of testing it.

**Comment by gety9** [comment]
@darkstego 

tested, problem solved, thank you for fast response and great project!
